name: cdk-validate

on:
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/cdk-*.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validate:
    uses: ./.github/workflows/cdk-validate-reusable.yml
    with:
      aws_role_arn: ${{ vars.AWS_ROLE_ARN_PR }}
      upload_artifact: true
